#!/usr/bin/python3
import sys

ans = 0

for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans,end= "") # 計算結果を表示

if isinstance(ans, int): # int型の整数の約数を計算
    divisors1 = []
    for i in range(1, ans+1):
         if ans % i == 0:
             divisors1.append(i)
    print(divisors1,end= "") # int型の整数の約数の計算結果を表示
elif ans.is_integer()== True: # float型の整数の約数を計算
    ans1 = int(ans) # float型からint型に変換
    divisors1 = []
    for i in range(1, ans1+1):
         if ans % i == 0:
             divisors1.append(i)
    print(divisors1,end= "") # float型の整数の約数の計算結果を表示
else: # 小数の処理
    print("No divisors.", end= "")

if isinstance(ans, int): # int型の整数の素因数分解を計算
    def prime_f_list(ans):
       divisors2 = []
       for prime in range(2, ans+1):
           while (ans % prime) == 0:
               divisors2.append(prime)
               ans //= prime
       return divisors2          
    print(prime_f_list(ans)) # int型の整数の素因数分解の計算結果を表示
elif ans.is_integer()== True: # float型の整数の素因数分解を計算
    ans2 = int(ans) # float型からint型に変換
    def prime_f_list(ans2):
       divisors2 = []
       for prime in range(2, ans2+1):
           while (ans2 % prime) == 0:
               divisors2.append(prime)
               ans2 //= prime
       return divisors2
    print(prime_f_list(ans2)) # float型の素因数分解の約数の計算結果を表示
else: # 小数の処理
    print("Prime factorization is not possible.")
